const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  REMOVE_CART_ITEM_ALL: 'REMOVE_CART_ITEM_ALL',
  CLEAR_CART: 'CLEAR_CART',
};

export default CartActionTypes;
